import type { NextPage } from "next";
import Head from "next/head";
import Title from "../components/home/title";
import Progress from "../components/home/progress";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Progress />

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="http://localhost:3000/">index.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>

        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
