import type { NextPage } from "next";
import Head from "next/head";
import Title from "../components/home/title";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  if (typeof window !== "undefined") {
    window.onscroll = function () {
      myFunction();
    };
  }

  function myFunction() {
    var winScroll =
      document.body.scrollTop || document.documentElement.scrollTop;
    var height =
      document.documentElement.scrollHeight -
      document.documentElement.clientHeight;
    var scrolled = (winScroll / height) * 100;
    const myBar = document.getElementById("myBar") as HTMLParagraphElement;
    if (myBar !== undefined) {
      myBar.style.width = scrolled + "%";
    }
  }

  return (
    <>
      <div className={styles.progress_container}>
        <div className={styles.progress_bar} id="myBar"></div>
      </div>

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="http://localhost:3000/">index.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </main>

        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />
        <Title />

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
